name       : httping
version    : 2.4.0
release    : 1
homepage   : http://www.vanheusden.com/httping/
source     :
    - https://github.com/flok99/httping/archive/v2.4.tar.gz : 0c3ab890b83652c2a33d27b114d78147933745e8261ea5b8dd06ddc6fef95f39
license    : GPL-2.0
summary    : Httping is like 'ping' but for http-requests.
builddeps  :
description: |
    Give it an url, and it'll show you how long it takes to connect, send a request and retrieve the reply (only the headers). Be aware that the transmission across the network also takes time! So it measures the latency of the webserver + network.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install