name       : httping
version    : 1.5.1
release    : 4
homepage   : http://www.vanheusden.com/httping/
source     :
    - https://www.vanheusden.com/httping/httping-1.5.1.tgz : a5496515883a7708c348d7f124eaac5bf7039feba2a3c8a7c30fd3a80a042504
license    : GPL-2.0-or-later
component  : network.util
summary    : Httping is like 'ping' but for http-requests.
description: |
    Give it an url, and it'll show you how long it takes to connect, send a request and retrieve the reply (only the headers). Be aware that the transmission across the network also takes time! So it measures the latency of the webserver + network.
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
