name       : httping
version    : 2.5.0
release    : 2
homepage   : http://www.vanheusden.com/httping/
source     :
    - https://github.com/flok99/httping/archive/v2.5.tar.gz : 2ad423097fa7a0d2d20a387050e34374326a703dddce897e152a8341e47ea500
license    : GPL-2.0
component  : network.util
summary    : Httping is like 'ping' but for http-requests.
description: |
    Give it an url, and it'll show you how long it takes to connect, send a request and retrieve the reply (only the headers). Be aware that the transmission across the network also takes time! So it measures the latency of the webserver + network.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
